### ISSUE TITLE
Issue #1 - User can add a todo.

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/react-todo-app#2]
## 💰 Feature

User can add a todo.

## 🗒️ Notes

This will require me to set up a route on the back-end to add todos to the database. I also might as well set up a route to retrieve the todos as well so that the user can view their todos as they add them. (Why did I want to make this minor project full-stack again?)

For the front end, I'll need to create a basic page structure and make an extremely simple header, and make some components for an input box and a todo list.

#### Back-End
- [x] Create a post route on the server.
- [x] Expand the post route to insert a new todo into the database.
- [x] Create a get route on the server.
- [x] Expand the get route to retrieve all todos from the database.
- [x] Test everything.

#### Front-End
- [x] Create a basic page layout.
- [x] Create a basic header.
- [x] Add some extremely basic styling.
- [x] Create a component for the input
- [x] Create a component for the todo list.
- [x] Expand the InputBox component to update state with the todo on changes.
- [x] Expand the InputBox component to send a post request to the server when the submit button is clicked.
- [x] Make everything look nice.
- [x] Test everything.
