### ISSUE TITLE
Issue #3 - User can 'complete' a todo

### ISSUE THREAD

**Issue by ChrisGitmed** [ChrisGitmed/react-todo-app#6]
## 💰 Feature

User can 'complete' their todos

## 🗒️ Notes

For this, I'll need to add a post route to the server, which updates the DB to toggle the isCompleted column of the todos table. I'll also need to add a way to show that the todo is completed in the front-end

#### Back-End
- [x] Add a put route to the server.
- [x] Enhance the post route to update the isCompleted property of a specific todo.
- [x] Test everything; Kill all bugs.

#### Front-End
- [x] Add a checkmark to be shown if the todo is completed.
- [x] Add an event listener for clicks on each todo to toggle the isCompleted property.
- [x] Expand the toggleClick handler to fetch a put request to the server.
- [x] BUG FIX: TodoList should render again upon completion of the put request.
- [x] Make it look nice.
- [x] Test everything; Kill all bugs.
